#!/bin/sh
#
# prey-agent init script
#
# chkconfig:   2345 20 80
# description: starts prey anti-theft agent
#

### BEGIN INIT INFO
# Provides:          prey-agent
# Required-Start:    $local_fs $remote_fs $syslog
# Required-Stop:     $local_fs $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts prey anti-theft agent
# Description:       starts prey anti-theft agent using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON="{{prey_bin}}"
DAEMON_OPTS=""
WORKING_DIR="{{root_path}}"
USER="{{user}}"
NAME=prey-agent
DESC="Prey Anti-Theft Agent"

# Include defaults if available
if [ -f /etc/default/prey-agent ]; then
	. /etc/default/prey-agent
fi

test -x $DAEMON || exit 0

set -e
. /lib/lsb/init-functions

start(){
	start-stop-daemon --start --quiet -d $WORKING_DIR -c $USER --pidfile /var/run/$NAME.pid \
		--exec $DAEMON --background --make-pidfile -- $DAEMON_OPTS || true
}

stop(){
	start-stop-daemon --stop --signal QUIT --quiet --pidfile /var/run/$NAME.pid || true
}

case "$1" in
	start)
		echo -n "Starting $DESC: "
		start
		echo "$NAME."
		;;

	stop)
		echo -n "Stopping $DESC: "
		stop
		echo "$NAME."
		;;

	restart|force-reload)
		echo -n "Restarting $DESC: "
		stop
		sleep 1
		start
		echo "$NAME."
		;;

	status)
		status_of_proc -p /var/run/$NAME.pid "$DAEMON" "$NAME" && exit 0 || exit $?
		;;

	*)
		echo "Usage: $NAME {start|stop|restart|force-reload|status}" >&2
		exit 1
		;;
esac

exit 0
