name: Node.js CI

on: push
  schedule:
    - cron:  '0 12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: npm install
    - run: node_modules/mocha/bin/mocha test
